#!/usr/bin/env python3
"""Publication-style plots for AMOS 2026 GAT full-action Monte Carlo results.

This script consumes the Monte Carlo output tree generated by the AMOS 2026
GAT reward-sweep evaluations. If the detailed post-processing tables are not
available yet, it runs analyze_gat_reward_sweep_mc_detailed.py first, then
creates paper-ready figures in the visual style of the Breckenridge/AAS GNC
alpha-sweep plots.
"""

from __future__ import annotations

import argparse
import math
import re
import subprocess
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.colors import Normalize
from matplotlib.patches import Ellipse
from matplotlib.lines import Line2D
from matplotlib.ticker import AutoMinorLocator

POLICY_ORDER = [
    "00d100i",
    "10d90i",
    "20d80i",
    "30d70i",
    "40d60i",
    "50d50i",
    "75d25i",
    "100d00i",
]
ACTION_COLORS = {
    "image": "#2C7BB6",
    "charge": "#ABDDA4",
    "downlink": "#FDAE61",
    "desat": "#D7191C",
}

# Breckenridge/GNC-inspired visual style.
COLORMAP = "plasma"
LINEWIDTH = 2.8
FILL_ALPHA = 0.11
ERRORBAR_ALPHA = 0.68
CAPSIZE = 4
GRID_ALPHA = 0.24
DPI = 320
LABEL_FONTSIZE = 17
TICK_FONTSIZE = 13
LEGEND_FONTSIZE = 13

TITLE_FONTSIZE = 16
SHORT_LABELS = {
    "score_ground_value_100d00i": "Ground-value reward",
    "image_to_next_reward_downlink_latency_median_sec": "Image-to-downlink latency [min]",
}


def parse_args() -> argparse.Namespace:
    default_root = Path(
        "/Users/dahu1128/rllib_results/amos2026_target_gnn_results/"
        "gat_full_actions_eval_100d00i_smoke_2h_20260601T184244Z"
    )
    parser = argparse.ArgumentParser(
        description="Create AMOS 2026 publication-style GAT MC figures."
    )
    parser.add_argument("--input-root", type=Path, default=default_root)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Defaults to <input-root>/analysis_research_plots.",
    )
    parser.add_argument(
        "--detailed-dir",
        type=Path,
        default=None,
        help="Defaults to <input-root>/analysis_detailed.",
    )
    parser.add_argument(
        "--expected-seeds",
        default="0:100",
        help="Expected Python-style seed range passed to the detailed analyzer.",
    )
    parser.add_argument(
        "--storage-capacity-images",
        type=float,
        default=50.0,
        help="Image-equivalent storage capacity for detailed downlink estimates.",
    )
    parser.add_argument(
        "--force-detailed",
        action="store_true",
        help="Regenerate detailed analysis tables before plotting.",
    )
    parser.add_argument(
        "--no-colorbar",
        action="store_true",
        help="Do not add alpha colorbars to the alpha-sweep figures.",
    )
    parser.add_argument(
        "--comparison-root",
        type=Path,
        default=None,
        help="Optional 100-target MC root to compare against the input root.",
    )
    parser.add_argument(
        "--comparison-output-dir",
        type=Path,
        default=None,
        help="Defaults to <input-root>/analysis_research_plots_compare_100targets.",
    )
    return parser.parse_args()


def policy_alpha(policy_tag: str) -> float:
    """Return downlink reward weight alpha from tags like 20d80i."""
    match = re.fullmatch(r"(\d+)d(\d+)i", policy_tag)
    if not match:
        raise ValueError(f"Cannot parse reward-mix tag as alpha: {policy_tag}")
    downlink_weight = float(match.group(1))
    imaging_weight = float(match.group(2))
    total = downlink_weight + imaging_weight
    if total <= 0:
        raise ValueError(f"Invalid reward-mix tag: {policy_tag}")
    return downlink_weight / total


def setup_style() -> None:
    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
            "mathtext.fontset": "dejavuserif",
            "axes.labelsize": LABEL_FONTSIZE,
            "axes.titlesize": TITLE_FONTSIZE,
            "xtick.labelsize": TICK_FONTSIZE,
            "ytick.labelsize": TICK_FONTSIZE,
            "legend.fontsize": LEGEND_FONTSIZE,
            "figure.dpi": 140,
            "savefig.dpi": DPI,
            "axes.linewidth": 1.1,
        }
    )


def finish_axis(ax: plt.Axes, xlabel: str | None = None) -> None:
    if xlabel:
        ax.set_xlabel(xlabel)
    ax.minorticks_on()
    ax.grid(True, alpha=GRID_ALPHA)
    ax.grid(True, which="minor", alpha=GRID_ALPHA * 0.55)
    ax.xaxis.set_minor_locator(AutoMinorLocator(2))
    for spine in ax.spines.values():
        spine.set_linewidth(1.1)


def save_figure(fig: plt.Figure, out_dir: Path, stem: str) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for ext in ("png", "pdf"):
        fig.savefig(out_dir / f"{stem}.{ext}", bbox_inches="tight", dpi=DPI, pad_inches=0.06)
    plt.close(fig)


def mean_col(df: pd.DataFrame, base: str) -> str:
    col = f"{base}_mean"
    if col not in df.columns:
        raise KeyError(f"Missing expected column {col}")
    return col


def std_col(df: pd.DataFrame, base: str) -> str:
    col = f"{base}_std"
    if col not in df.columns:
        raise KeyError(f"Missing expected column {col}")
    return col


def normalize_summary(summary: pd.DataFrame) -> pd.DataFrame:
    summary = summary.copy()
    summary = summary[summary["policy_tag"].isin(POLICY_ORDER)].copy()
    if "n_runs" in summary.columns:
        summary = summary[pd.to_numeric(summary["n_runs"], errors="coerce").fillna(0) > 0]
    summary["policy_tag"] = pd.Categorical(
        summary["policy_tag"], categories=POLICY_ORDER, ordered=True
    )
    summary = summary.sort_values("policy_tag").reset_index(drop=True)
    summary["alpha"] = summary["policy_tag"].astype(str).map(policy_alpha)
    return summary


def normalize_policy_table(table: pd.DataFrame) -> pd.DataFrame:
    table = table.copy()
    if "policy_tag" not in table.columns:
        return table
    table = table[table["policy_tag"].isin(POLICY_ORDER)].copy()
    table["policy_tag"] = pd.Categorical(
        table["policy_tag"], categories=POLICY_ORDER, ordered=True
    )
    return table.sort_values("policy_tag").reset_index(drop=True)


def read_csv_or_empty(path: Path) -> pd.DataFrame:
    if not path.exists() or path.stat().st_size <= 1:
        return pd.DataFrame()
    return pd.read_csv(path)


def run_detailed_if_needed(
    input_root: Path,
    detailed_dir: Path,
    expected_seeds: str,
    storage_capacity_images: float,
    force: bool,
) -> None:
    required = [
        detailed_dir / "detailed_per_run.csv",
        detailed_dir / "detailed_summary_by_policy.csv",
        detailed_dir / "action_distribution_by_policy.csv",
        detailed_dir / "downlink_summary_by_policy.csv",
        detailed_dir / "action_id_distribution_by_policy.csv",
        detailed_dir / "image_candidate_slot_summary_by_policy.csv",
        detailed_dir / "metric_definitions.json",
    ]
    if not force and all(path.exists() for path in required):
        print(f"Reusing detailed analysis in {detailed_dir}")
        return

    script = Path(__file__).with_name("analyze_gat_reward_sweep_mc_detailed.py")
    cmd = [
        sys.executable,
        str(script),
        "--input-root",
        str(input_root),
        "--output-dir",
        str(detailed_dir),
        "--expected-seeds",
        expected_seeds,
        "--storage-capacity-images",
        str(storage_capacity_images),
    ]
    print("Running detailed analyzer:")
    print(" ".join(cmd))
    subprocess.run(cmd, check=True)


def add_alpha_colorbar(fig: plt.Figure, ax: plt.Axes, norm: Normalize, cmap, enabled: bool) -> None:
    if not enabled:
        return
    sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax, pad=0.035, fraction=0.04)
    cbar.set_label(r"Downlink reward weight $\alpha$", labelpad=8)


def plot_alpha_metric(
    summary: pd.DataFrame,
    out_dir: Path,
    metric: str,
    ylabel: str,
    stem: str,
    marker: str = "o",
    title: str | None = None,
    ylim: tuple[float, float] | None = None,
    colorbar: bool = True,
) -> None:
    cmap = plt.get_cmap(COLORMAP)
    norm = Normalize(0.0, 1.0)
    x = summary["alpha"].to_numpy(dtype=float)
    y = summary[mean_col(summary, metric)].to_numpy(dtype=float)
    ystd = summary[std_col(summary, metric)].to_numpy(dtype=float)

    fig, ax = plt.subplots(figsize=(7.6, 4.55), constrained_layout=True)
    ax.fill_between(x, y - ystd, y + ystd, color="tab:blue", alpha=FILL_ALPHA, zorder=1)
    ax.errorbar(
        x,
        y,
        yerr=ystd,
        fmt="none",
        ecolor="0.2",
        elinewidth=1.45,
        capsize=CAPSIZE,
        alpha=ERRORBAR_ALPHA,
        zorder=3,
    )
    ax.plot(x, y, color="0.18", linewidth=1.1, alpha=0.45, zorder=2)
    ax.scatter(
        x,
        y,
        c=x,
        cmap=cmap,
        norm=norm,
        marker=marker,
        s=92 if marker != "*" else 170,
        edgecolor="k",
        linewidth=0.8,
        zorder=4,
    )
    if title:
        ax.set_title(title)
    elif metric == "score_ground_value_100d00i":
        ax.set_title(r"Evaluated with $\alpha = 1.0$")
    elif metric == "mean_est_images_removed_per_storage_downlink":
        ax.set_title("Per successful storage-reducing downlink")
    ax.set_ylabel(ylabel)
    ax.set_xlim(-0.025, 1.025)
    if ylim:
        ax.set_ylim(*ylim)
    finish_axis(ax, r"Downlink reward weight $\alpha$")
    add_alpha_colorbar(fig, ax, norm, cmap, colorbar)
    save_figure(fig, out_dir, stem)


def plot_ground_value_score_boxplot(
    per_run: pd.DataFrame, out_dir: Path, colorbar: bool
) -> None:
    required = {"policy_tag", "score_ground_value_100d00i"}
    if per_run.empty or not required.issubset(per_run.columns):
        return

    data = per_run[per_run["policy_tag"].isin(POLICY_ORDER)].copy()
    if "state" in data.columns:
        data = data[data["state"] == "completed"].copy()
    cmap = plt.get_cmap(COLORMAP)
    norm = Normalize(0.0, 1.0)

    values = []
    positions = []
    alphas = []
    for policy_tag in POLICY_ORDER:
        policy_values = (
            pd.to_numeric(
                data.loc[data["policy_tag"] == policy_tag, "score_ground_value_100d00i"],
                errors="coerce",
            )
            .dropna()
            .to_numpy(dtype=float)
        )
        if policy_values.size == 0:
            continue
        values.append(policy_values)
        alpha = policy_alpha(policy_tag)
        positions.append(alpha)
        alphas.append(alpha)

    if not values:
        return

    fig, ax = plt.subplots(figsize=(8.7, 5.2), constrained_layout=True)
    box = ax.boxplot(
        values,
        positions=positions,
        widths=0.055,
        patch_artist=True,
        showmeans=True,
        boxprops={"linewidth": 1.1, "edgecolor": "0.15"},
        whiskerprops={"color": "0.25", "linewidth": 1.05},
        capprops={"color": "0.25", "linewidth": 1.05},
        medianprops={"color": "0.05", "linewidth": 1.4},
        meanprops={
            "marker": "D",
            "markerfacecolor": "white",
            "markeredgecolor": "0.05",
            "markersize": 5.5,
        },
        flierprops={
            "marker": "o",
            "markerfacecolor": "none",
            "markeredgecolor": "0.05",
            "markersize": 5.2,
            "linestyle": "none",
            "alpha": 0.85,
        },
    )
    for patch, alpha in zip(box["boxes"], alphas, strict=True):
        patch.set_facecolor(cmap(norm(alpha)))
        patch.set_alpha(0.72)

    for alpha, policy_values in zip(alphas, values, strict=True):
        jitter = np.linspace(-0.018, 0.018, len(policy_values))
        ax.scatter(
            np.full(len(policy_values), alpha) + jitter,
            policy_values,
            color=cmap(norm(alpha)),
            s=13,
            alpha=0.34,
            edgecolor="none",
            zorder=2,
        )

    ax.set_title("AMOS 2026 GAT Policies Scored With Common 100d00i Reward")
    ax.set_ylabel("Ground-value score")
    ax.set_xlim(-0.06, 1.06)
    ax.set_xticks(alphas)
    ax.set_xticklabels([f"{alpha:g}" for alpha in alphas])
    finish_axis(ax, r"Downlink reward weight $\alpha$")
    handles = [
        Line2D(
            [0],
            [0],
            marker="D",
            linestyle="none",
            markerfacecolor="white",
            markeredgecolor="0.05",
            markersize=5.5,
            label="Mean",
        ),
        Line2D(
            [0],
            [0],
            marker="o",
            linestyle="none",
            markerfacecolor="none",
            markeredgecolor="0.05",
            markersize=5.2,
            label="1.5-IQR outlier",
        ),
    ]
    ax.legend(handles=handles, loc="lower left", framealpha=0.9, fontsize=11)
    add_alpha_colorbar(fig, ax, norm, cmap, colorbar)
    save_figure(fig, out_dir, "ground_value_score_boxplot_common_100d00i")


def plot_reward_images_combined(summary: pd.DataFrame, out_dir: Path, colorbar: bool) -> None:
    cmap = plt.get_cmap(COLORMAP)
    norm = Normalize(0.0, 1.0)
    x = summary["alpha"].to_numpy(dtype=float)
    series = [
        ("score_ground_value_100d00i", "Reward", "o", 88),
        ("illuminated_images", "Illuminated images", "*", 170),
        ("confirmed_illuminated_images", "Confirmed images", "v", 95),
    ]

    fig, ax = plt.subplots(figsize=(8.7, 4.95), constrained_layout=True)
    for metric, label, marker, size in series:
        y = summary[mean_col(summary, metric)].to_numpy(dtype=float)
        ystd = summary[std_col(summary, metric)].to_numpy(dtype=float)
        ax.fill_between(x, y - ystd, y + ystd, alpha=FILL_ALPHA * 0.7, zorder=1)
        ax.errorbar(
            x,
            y,
            yerr=ystd,
            fmt="none",
            ecolor="0.2",
            elinewidth=1.35,
            capsize=CAPSIZE,
            alpha=ERRORBAR_ALPHA,
            zorder=3,
        )
        ax.scatter(
            x,
            y,
            c=x,
            cmap=cmap,
            norm=norm,
            marker=marker,
            s=size,
            edgecolor="k",
            linewidth=0.8,
            zorder=4,
            label=label,
        )
    ax.set_ylabel("Count / reward")
    ax.set_xlim(-0.025, 1.025)
    finish_axis(ax, r"Downlink reward weight $\alpha$")
    ax.legend(loc="upper center", ncol=3, framealpha=0.92, fontsize=12)
    add_alpha_colorbar(fig, ax, norm, cmap, colorbar)
    save_figure(fig, out_dir, "reward_images_confirmed_vs_alpha")


def plot_image_status(summary: pd.DataFrame, out_dir: Path, colorbar: bool) -> None:
    cmap = plt.get_cmap(COLORMAP)
    norm = Normalize(0.0, 1.0)
    x = summary["alpha"].to_numpy(dtype=float)
    metrics = [
        ("illuminated_images", "Total illuminated", "o"),
        ("confirmed_illuminated_images", "Confirmed/downlinked", "v"),
        ("pending_illuminated_images_onboard", "Pending illuminated onboard", "s"),
        ("pending_images_onboard", "Pending total onboard", "D"),
    ]
    fig, ax = plt.subplots(figsize=(8.5, 5.0), constrained_layout=True)
    for metric, label, marker in metrics:
        y = summary[mean_col(summary, metric)].to_numpy(dtype=float)
        ystd = summary[std_col(summary, metric)].to_numpy(dtype=float)
        ax.plot(x, y, color="0.18", linewidth=0.85, alpha=0.35, zorder=1)
        ax.errorbar(
            x,
            y,
            yerr=ystd,
            fmt="none",
            ecolor="0.25",
            elinewidth=1.1,
            capsize=CAPSIZE,
            alpha=0.45,
            zorder=2,
        )
        ax.scatter(
            x,
            y,
            c=x,
            cmap=cmap,
            norm=norm,
            marker=marker,
            s=75,
            edgecolor="k",
            linewidth=0.75,
            zorder=3,
            label=label,
        )
    ax.set_ylabel("Images [count]")
    finish_axis(ax, r"Downlink reward weight $\alpha$")
    ax.legend(loc="best", framealpha=0.92)
    add_alpha_colorbar(fig, ax, norm, cmap, colorbar)
    save_figure(fig, out_dir, "image_status_vs_alpha")


def plot_action_distribution(actions: pd.DataFrame, out_dir: Path) -> None:
    actions = normalize_policy_table(actions)
    actions["alpha"] = actions["policy_tag"].astype(str).map(policy_alpha)
    labels = ["image", "charge", "downlink", "desat"]
    x = actions["alpha"].to_numpy(dtype=float)
    width = 0.075

    fig, ax = plt.subplots(figsize=(8.1, 5.05), constrained_layout=True)
    bottom = np.zeros(len(actions))
    for label in labels:
        values = actions[f"{label}_actions"].to_numpy(dtype=float)
        ax.bar(
            x,
            values,
            bottom=bottom,
            width=width,
            color=ACTION_COLORS[label],
            edgecolor="0.15",
            linewidth=0.35,
            label=label.capitalize(),
            alpha=0.92,
        )
        bottom += values
    ax.set_ylabel("Action count across 100 seeds")
    ax.set_xlim(-0.06, 1.06)
    finish_axis(ax, r"Downlink reward weight $\alpha$")
    ax.legend(loc="lower center", ncol=4, framealpha=0.92)
    save_figure(fig, out_dir, "action_distribution_stacked_counts")

    # Fraction version is easier to compare behavior independent of episode length.
    totals = actions[[f"{label}_actions" for label in labels]].sum(axis=1).replace(0.0, np.nan)
    fig, ax = plt.subplots(figsize=(8.1, 5.05), constrained_layout=True)
    bottom = np.zeros(len(actions))
    for label in labels:
        values = (actions[f"{label}_actions"] / totals).to_numpy(dtype=float)
        ax.bar(
            x,
            values,
            bottom=bottom,
            width=width,
            color=ACTION_COLORS[label],
            edgecolor="0.15",
            linewidth=0.35,
            label=label.capitalize(),
            alpha=0.92,
        )
        bottom += np.nan_to_num(values)
    ax.set_ylabel("Action fraction")
    ax.set_xlim(-0.06, 1.06)
    ax.set_ylim(0, 1.0)
    finish_axis(ax, r"Downlink reward weight $\alpha$")
    ax.legend(loc="lower center", ncol=4, framealpha=0.92)
    save_figure(fig, out_dir, "action_distribution_stacked_fraction")


def plot_action_outcome_stacked_fraction(per_run: pd.DataFrame, out_dir: Path) -> None:
    required = {
        "policy_tag",
        "illuminated_images",
        "image_action_count_steps_csv",
        "downlink_action_count_steps_csv",
        "downlink_positive_reward_count",
        "charge_action_count_steps_csv",
        "desat_action_count_steps_csv",
    }
    if per_run.empty or not required.issubset(per_run.columns):
        return

    data = per_run[per_run["policy_tag"].isin(POLICY_ORDER)].copy()
    numeric_cols = sorted(required - {"policy_tag"})
    for col in numeric_cols:
        data[col] = pd.to_numeric(data[col], errors="coerce").fillna(0.0)

    grouped = data.groupby("policy_tag", observed=True)[numeric_cols].sum()
    rows = []
    for policy_tag in POLICY_ORDER:
        if policy_tag not in grouped.index:
            continue
        row = grouped.loc[policy_tag]
        image_actions = float(row["image_action_count_steps_csv"])
        downlink_actions = float(row["downlink_action_count_steps_csv"])
        total_actions = (
            image_actions
            + downlink_actions
            + float(row["charge_action_count_steps_csv"])
            + float(row["desat_action_count_steps_csv"])
        )
        if total_actions <= 0:
            continue
        illuminated = min(float(row["illuminated_images"]), image_actions)
        useful_downlinks = min(float(row["downlink_positive_reward_count"]), downlink_actions)
        rows.append(
            {
                "policy_tag": policy_tag,
                "alpha": policy_alpha(policy_tag),
                "image_illuminated": illuminated / total_actions,
                "image_not_illuminated": max(image_actions - illuminated, 0.0)
                / total_actions,
                "downlink_useful": useful_downlinks / total_actions,
                "downlink_no_value": max(downlink_actions - useful_downlinks, 0.0)
                / total_actions,
            }
        )

    outcome = pd.DataFrame(rows)
    if outcome.empty:
        return

    x = outcome["alpha"].to_numpy(dtype=float)
    series = [
        ("image_illuminated", "Image illuminated", "#2C7BB6"),
        ("image_not_illuminated", "Image not illuminated", "#A6CEE3"),
        ("downlink_useful", "Downlink useful", "#FDAE61"),
        ("downlink_no_value", "Downlink no value", "#D95F0E"),
    ]

    fig, ax = plt.subplots(figsize=(8.6, 5.25), constrained_layout=True)
    bottom = np.zeros(len(outcome))
    for metric, label, color in series:
        values = outcome[metric].to_numpy(dtype=float)
        ax.bar(
            x,
            values,
            bottom=bottom,
            width=0.075,
            color=color,
            edgecolor="0.15",
            linewidth=0.35,
            label=label,
            alpha=0.93,
        )
        bottom += values

    ax.set_ylabel("Action fraction")
    ax.set_xlim(-0.06, 1.06)
    ax.set_ylim(0, 1.0)
    finish_axis(ax, r"Downlink reward weight $\alpha$")
    ax.legend(
        loc="upper center",
        bbox_to_anchor=(0.5, -0.16),
        ncol=2,
        framealpha=0.93,
        columnspacing=1.5,
        handletextpad=0.55,
    )
    save_figure(fig, out_dir, "action_distribution_outcome_stacked_fraction")


def plot_downlink_usefulness(downlinks: pd.DataFrame, out_dir: Path, colorbar: bool) -> None:
    downlinks = normalize_summary(downlinks)
    cmap = plt.get_cmap(COLORMAP)
    norm = Normalize(0.0, 1.0)
    x = downlinks["alpha"].to_numpy(dtype=float)

    fig, ax = plt.subplots(figsize=(9.15, 4.95), constrained_layout=True)
    left_metric = "downlink_success_rate_reward_proxy"
    y = downlinks[mean_col(downlinks, left_metric)].to_numpy(dtype=float)
    ystd = downlinks[std_col(downlinks, left_metric)].to_numpy(dtype=float)
    ax.fill_between(x, y - ystd, y + ystd, color="tab:blue", alpha=FILL_ALPHA, zorder=1)
    ax.errorbar(x, y, yerr=ystd, fmt="none", ecolor="0.2", capsize=CAPSIZE, alpha=0.65)
    ax.scatter(
        x,
        y,
        c=x,
        cmap=cmap,
        norm=norm,
        marker="s",
        s=82,
        edgecolor="k",
        linewidth=0.8,
        label="Reward-bearing downlink fraction",
        zorder=3,
    )
    ax.set_ylabel("Useful downlink fraction")
    ax.set_ylim(-0.02, 1.02)
    finish_axis(ax, r"Downlink reward weight $\alpha$")

    ax2 = ax.twinx()
    value_metric = "mean_ground_value_per_positive_downlink"
    y2 = downlinks[mean_col(downlinks, value_metric)].to_numpy(dtype=float)
    y2std = downlinks[std_col(downlinks, value_metric)].to_numpy(dtype=float)
    ax2.fill_between(
        x,
        y2 - y2std,
        y2 + y2std,
        color="tab:orange",
        alpha=FILL_ALPHA,
        zorder=1,
    )
    ax2.errorbar(x, y2, yerr=y2std, fmt="none", ecolor="0.35", capsize=CAPSIZE, alpha=0.55)
    ax2.scatter(
        x,
        y2,
        c=x,
        cmap=cmap,
        norm=norm,
        marker="D",
        s=76,
        edgecolor="k",
        linewidth=0.8,
        label="Mean value per useful downlink",
        zorder=3,
    )
    ax2.set_ylabel("Value/useful downlink", labelpad=10)
    handles1, labels1 = ax.get_legend_handles_labels()
    handles2, labels2 = ax2.get_legend_handles_labels()
    ax.legend(
        handles1 + handles2,
        labels1 + labels2,
        loc="upper center",
        ncol=2,
        framealpha=0.92,
    )
    add_alpha_colorbar(fig, ax, norm, cmap, colorbar)
    save_figure(fig, out_dir, "downlink_usefulness_vs_alpha")

    plot_alpha_metric(
        downlinks,
        out_dir,
        "mean_est_images_removed_per_storage_downlink",
        "Mean downlinked images",
        "images_removed_per_downlink_vs_alpha",
        marker="v",
        colorbar=colorbar,
    )


def summarize_per_run_metrics(per_run: pd.DataFrame, metrics: list[str]) -> pd.DataFrame:
    per_run = per_run[per_run["policy_tag"].isin(POLICY_ORDER)].copy()
    rows: list[dict[str, float | str]] = []
    for policy_tag in POLICY_ORDER:
        policy_rows = per_run[per_run["policy_tag"] == policy_tag]
        if policy_rows.empty:
            continue
        row: dict[str, float | str] = {
            "policy_tag": policy_tag,
            "alpha": policy_alpha(policy_tag),
        }
        for metric in metrics:
            if metric not in policy_rows.columns:
                raise KeyError(f"Missing expected per-run column {metric}")
            values = (
                pd.to_numeric(policy_rows[metric], errors="coerce")
                .replace([np.inf, -np.inf], np.nan)
                .dropna()
            )
            row[f"{metric}_mean"] = float(values.mean()) if len(values) else np.nan
            row[f"{metric}_std"] = float(values.std(ddof=1)) if len(values) > 1 else 0.0
        rows.append(row)
    return pd.DataFrame(rows)


def plot_downlink_value_density(
    per_run: pd.DataFrame, out_dir: Path, colorbar: bool
) -> None:
    metrics = [
        "downlink_success_rate_reward_proxy",
        "mean_ground_value_per_positive_downlink",
        "mean_ground_value_per_downlink_action",
    ]
    summary = summarize_per_run_metrics(per_run, metrics)
    if summary.empty:
        return

    cmap = plt.get_cmap(COLORMAP)
    norm = Normalize(0.0, 1.0)
    plot_specs = [
        (
            "mean_ground_value_per_positive_downlink",
            "Ground reward per useful downlink",
            "Value density of reward-bearing downlinks",
            "downlink_usefulness_vs_value_per_useful_downlink",
        ),
        (
            "mean_ground_value_per_downlink_action",
            "Ground reward per downlink action",
            "Value density across all downlinks",
            "downlink_usefulness_vs_value_per_downlink",
        ),
    ]

    for x_metric, xlabel, title, stem in plot_specs:
        valid = summary.dropna(
            subset=[
                f"{x_metric}_mean",
                "downlink_success_rate_reward_proxy_mean",
            ]
        )
        if valid.empty:
            continue
        alpha = valid["alpha"].to_numpy(dtype=float)
        x = valid[f"{x_metric}_mean"].to_numpy(dtype=float)
        xstd = np.nan_to_num(valid[f"{x_metric}_std"].to_numpy(dtype=float))
        y = valid["downlink_success_rate_reward_proxy_mean"].to_numpy(dtype=float)
        ystd = np.nan_to_num(
            valid["downlink_success_rate_reward_proxy_std"].to_numpy(dtype=float)
        )

        fig, ax = plt.subplots(figsize=(7.95, 4.9), constrained_layout=True)
        ax.errorbar(
            x,
            y,
            xerr=xstd,
            yerr=ystd,
            fmt="none",
            ecolor="0.28",
            elinewidth=1.2,
            capsize=CAPSIZE,
            alpha=0.58,
            zorder=1,
        )
        ax.plot(x, y, color="0.25", linewidth=1.05, alpha=0.4, zorder=2)
        ax.scatter(
            x,
            y,
            c=alpha,
            cmap=cmap,
            norm=norm,
            marker="o",
            s=94,
            edgecolor="k",
            linewidth=0.8,
            zorder=3,
        )
        ax.set_title(title)
        ax.set_xlabel(xlabel)
        ax.set_ylabel("Useful downlink fraction")
        xmin = float(np.nanmin(x - xstd))
        xmax = float(np.nanmax(x + xstd))
        pad = max((xmax - xmin) * 0.12, 0.5)
        ax.set_xlim(max(0.0, xmin - pad), xmax + pad)
        ax.set_ylim(-0.02, 1.02)
        finish_axis(ax)
        add_alpha_colorbar(fig, ax, norm, cmap, colorbar)
        save_figure(fig, out_dir, stem)


def plot_action_outcome_boxplot(per_run: pd.DataFrame, out_dir: Path) -> None:
    required = {
        "policy_tag",
        "illuminated_images",
        "image_action_count_steps_csv",
        "downlink_success_rate_reward_proxy",
    }
    if per_run.empty or not required.issubset(per_run.columns):
        return

    data = per_run[per_run["policy_tag"].isin(POLICY_ORDER)].copy()
    image_actions = pd.to_numeric(
        data["image_action_count_steps_csv"], errors="coerce"
    ).replace(0, np.nan)
    image_success = (
        pd.to_numeric(data["illuminated_images"], errors="coerce") / image_actions
    ).clip(0.0, 1.0)
    downlink_useful = pd.to_numeric(
        data["downlink_success_rate_reward_proxy"], errors="coerce"
    ).clip(0.0, 1.0)
    data["image_illuminated_fraction"] = image_success
    data["image_other_fraction"] = 1.0 - image_success
    data["downlink_useful_fraction"] = downlink_useful
    data["downlink_no_value_fraction"] = 1.0 - downlink_useful

    series = [
        ("image_illuminated_fraction", "Imaging: illuminated", "#2C7BB6", -0.033),
        ("image_other_fraction", "Imaging: not illuminated", "#A6CEE3", -0.011),
        ("downlink_useful_fraction", "Downlink: useful", "#FDAE61", 0.011),
        ("downlink_no_value_fraction", "Downlink: no value", "#D7191C", 0.033),
    ]
    alphas = [policy_alpha(tag) for tag in POLICY_ORDER if tag in set(data["policy_tag"])]

    fig, ax = plt.subplots(figsize=(10.6, 5.15), constrained_layout=True)
    for metric, label, color, offset in series:
        box_data = []
        positions = []
        for policy_tag in POLICY_ORDER:
            policy_data = data[data["policy_tag"] == policy_tag]
            if policy_data.empty:
                continue
            values = (
                pd.to_numeric(policy_data[metric], errors="coerce")
                .replace([np.inf, -np.inf], np.nan)
                .dropna()
                .to_numpy(dtype=float)
            )
            if values.size == 0:
                continue
            box_data.append(values)
            positions.append(policy_alpha(policy_tag) + offset)
        boxes = ax.boxplot(
            box_data,
            positions=positions,
            widths=0.015,
            patch_artist=True,
            showfliers=False,
            manage_ticks=False,
            boxprops={"linewidth": 0.8, "edgecolor": "0.16"},
            medianprops={"color": "0.05", "linewidth": 1.05},
            whiskerprops={"color": "0.25", "linewidth": 0.8},
            capprops={"color": "0.25", "linewidth": 0.8},
        )
        for patch in boxes["boxes"]:
            patch.set_facecolor(color)
            patch.set_alpha(0.78)

    ax.set_xticks(alphas)
    ax.set_xticklabels([f"{alpha:g}" for alpha in alphas])
    ax.set_xlim(-0.065, 1.065)
    ax.set_ylim(-0.02, 1.02)
    ax.set_ylabel("Fraction of actions")
    ax.set_title("Imaging and downlink action outcomes")
    legend_handles = [
        Line2D(
            [0],
            [0],
            marker="s",
            linestyle="none",
            markersize=11,
            markerfacecolor=color,
            markeredgecolor="0.16",
            label=label,
            alpha=0.88,
        )
        for _, label, color, _ in series
    ]
    ax.legend(
        handles=legend_handles,
        loc="center left",
        bbox_to_anchor=(1.01, 0.5),
        ncol=1,
        framealpha=0.93,
        handletextpad=0.5,
    )
    finish_axis(ax, r"Downlink reward weight $\alpha$")
    save_figure(fig, out_dir, "action_outcome_success_boxplot")


def plot_latency(downlinks: pd.DataFrame, out_dir: Path, colorbar: bool) -> None:
    downlinks = normalize_summary(downlinks)
    # Convert seconds to minutes for readability.
    for suffix in ("mean", "std"):
        col = f"image_to_next_reward_downlink_latency_median_sec_{suffix}"
        downlinks[f"latency_min_{suffix}"] = downlinks[col] / 60.0

    cmap = plt.get_cmap(COLORMAP)
    norm = Normalize(0.0, 1.0)
    x = downlinks["alpha"].to_numpy(dtype=float)
    y = downlinks["latency_min_mean"].to_numpy(dtype=float)
    ystd = downlinks["latency_min_std"].to_numpy(dtype=float)
    fig, ax = plt.subplots(figsize=(8.0, 4.7), constrained_layout=True)
    ax.fill_between(x, y - ystd, y + ystd, color="tab:purple", alpha=FILL_ALPHA)
    ax.errorbar(x, y, yerr=ystd, fmt="none", ecolor="0.25", capsize=CAPSIZE, alpha=0.65)
    ax.plot(x, y, color="0.18", linewidth=1.0, alpha=0.45)
    ax.scatter(
        x,
        y,
        c=x,
        cmap=cmap,
        norm=norm,
        marker="o",
        s=86,
        edgecolor="k",
        linewidth=0.8,
        zorder=3,
    )
    ax.set_ylabel("Median latency to value downlink [min]")
    finish_axis(ax, r"Downlink reward weight $\alpha$")
    add_alpha_colorbar(fig, ax, norm, cmap, colorbar)
    save_figure(fig, out_dir, "image_to_value_downlink_latency_vs_alpha")


def plot_imaging_timing(summary: pd.DataFrame, out_dir: Path, colorbar: bool) -> None:
    """Show how target selection translates into slew and action duration."""
    plot_alpha_metric(
        summary,
        out_dir,
        "mean_successful_imaging_slew_time_sec",
        "Mean successful imaging slew [s]",
        "successful_imaging_slew_time_vs_alpha",
        marker="o",
        colorbar=colorbar,
    )
    plot_alpha_metric(
        summary,
        out_dir,
        "mean_successful_imaging_action_duration_sec",
        "Mean successful imaging action duration [s]",
        "successful_imaging_action_duration_vs_alpha",
        marker="s",
        colorbar=colorbar,
    )

    cmap = plt.get_cmap(COLORMAP)
    norm = Normalize(0.0, 1.0)
    x = summary["alpha"].to_numpy(dtype=float)
    series = [
        ("mean_successful_imaging_slew_time_sec", "Successful slew", "o"),
        ("mean_unsuccessful_imaging_slew_time_sec", "Unsuccessful slew", "X"),
    ]
    fig, ax = plt.subplots(figsize=(8.0, 4.75), constrained_layout=True)
    for metric, label, marker in series:
        y = summary[mean_col(summary, metric)].to_numpy(dtype=float)
        ystd = summary[std_col(summary, metric)].to_numpy(dtype=float)
        ax.plot(x, y, color="0.25", linewidth=1.0, alpha=0.45)
        ax.errorbar(
            x,
            y,
            yerr=ystd,
            fmt="none",
            ecolor="0.25",
            elinewidth=1.2,
            capsize=CAPSIZE,
            alpha=ERRORBAR_ALPHA,
        )
        ax.scatter(
            x,
            y,
            c=x,
            cmap=cmap,
            norm=norm,
            marker=marker,
            s=86,
            edgecolor="k",
            linewidth=0.75,
            label=label,
            zorder=3,
        )
    ax.set_ylabel("Mean slew time [s]")
    ax.legend(framealpha=0.92)
    finish_axis(ax, r"Downlink reward weight $\alpha$")
    add_alpha_colorbar(fig, ax, norm, cmap, colorbar)
    save_figure(fig, out_dir, "successful_unsuccessful_imaging_slew_vs_alpha")


def plot_downlink_outcomes(
    downlinks: pd.DataFrame, out_dir: Path, colorbar: bool
) -> None:
    """Separate genuinely empty downlinks from nonempty failed transfers."""
    downlinks = normalize_summary(downlinks)
    x = downlinks["alpha"].to_numpy(dtype=float)
    success = downlinks[
        mean_col(downlinks, "downlink_success_rate_storage_proxy")
    ].to_numpy(dtype=float)
    empty = downlinks[
        mean_col(downlinks, "downlink_empty_at_command_fraction")
    ].to_numpy(dtype=float)
    nonempty_failed = downlinks[
        mean_col(downlinks, "downlink_nonempty_no_transfer_fraction")
    ].to_numpy(dtype=float)

    fig, ax = plt.subplots(figsize=(8.2, 4.8), constrained_layout=True)
    width = 0.075
    ax.bar(x, success, width=width, color="#2C7BB6", label="Storage reduced")
    ax.bar(x, empty, width=width, bottom=success, color="#FDAE61", label="Storage empty at command")
    ax.bar(
        x,
        nonempty_failed,
        width=width,
        bottom=success + empty,
        color="#D7191C",
        label="Nonempty, no transfer",
    )
    ax.set_ylim(0.0, 1.03)
    ax.set_ylabel("Fraction of downlink actions")
    ax.legend(loc="upper center", ncol=3, framealpha=0.92, fontsize=11)
    finish_axis(ax, r"Downlink reward weight $\alpha$")
    save_figure(fig, out_dir, "downlink_outcome_fraction_vs_alpha")

    cmap = plt.get_cmap(COLORMAP)
    norm = Normalize(0.0, 1.0)
    duration_series = [
        ("mean_successful_downlink_duration_sec", "Storage reduced", "o"),
        ("mean_empty_downlink_duration_sec", "Empty at command", "s"),
        ("mean_nonempty_no_transfer_downlink_duration_sec", "Nonempty, no transfer", "X"),
    ]
    fig, ax = plt.subplots(figsize=(8.3, 4.9), constrained_layout=True)
    ax.axhline(
        10.0,
        color="0.18",
        linewidth=1.15,
        linestyle=(0, (4, 3)),
        alpha=0.72,
        label="10 s minimum action",
        zorder=0,
    )
    for metric, label, marker in duration_series:
        y = downlinks[mean_col(downlinks, metric)].to_numpy(dtype=float)
        ystd = downlinks[std_col(downlinks, metric)].to_numpy(dtype=float)
        ax.plot(x, y, color="0.25", linewidth=0.9, alpha=0.38)
        ax.errorbar(
            x,
            y,
            yerr=ystd,
            fmt="none",
            ecolor="0.25",
            elinewidth=1.15,
            capsize=CAPSIZE,
            alpha=ERRORBAR_ALPHA,
        )
        ax.scatter(
            x,
            y,
            c=x,
            cmap=cmap,
            norm=norm,
            marker=marker,
            s=86,
            edgecolor="k",
            linewidth=0.75,
            label=label,
            zorder=3,
        )
    ax.set_ylabel("Mean downlink action duration [s]")
    ax.legend(framealpha=0.92)
    finish_axis(ax, r"Downlink reward weight $\alpha$")
    add_alpha_colorbar(fig, ax, norm, cmap, colorbar)
    save_figure(fig, out_dir, "downlink_duration_by_outcome_vs_alpha")


def plot_candidate_slot_behavior(
    candidates: pd.DataFrame, out_dir: Path, colorbar: bool
) -> None:
    """Plot use of ImageRSO action IDs 3..12 (candidate slots 0..9)."""
    if candidates.empty:
        return
    candidates = normalize_policy_table(candidates)
    cmap = plt.get_cmap(COLORMAP)
    norm = Normalize(0.0, 1.0)
    fig, ax = plt.subplots(figsize=(8.2, 4.8), constrained_layout=True)
    for tag in POLICY_ORDER:
        subset = candidates[candidates["policy_tag"] == tag].sort_values("candidate_slot")
        if subset.empty:
            continue
        alpha = policy_alpha(tag)
        ax.plot(
            subset["candidate_slot"],
            subset["fraction_image_actions"],
            color=cmap(norm(alpha)),
            marker="o",
            markersize=5.5,
            linewidth=1.8,
            alpha=0.9,
        )
    ax.set_xticks(range(10), [f"{slot}\n({slot + 3})" for slot in range(10)])
    ax.set_xlabel("Elevation-ordered candidate slot (discrete action ID)")
    ax.set_ylabel("Fraction of imaging actions")
    ax.set_title("Candidate slots are ascending in local elevation when fully populated")
    finish_axis(ax)
    add_alpha_colorbar(fig, ax, norm, cmap, colorbar)
    save_figure(fig, out_dir, "image_candidate_slot_frequency_vs_alpha")

    fig, ax = plt.subplots(figsize=(8.2, 4.8), constrained_layout=True)
    for tag in POLICY_ORDER:
        subset = candidates[candidates["policy_tag"] == tag].sort_values("candidate_slot")
        if subset.empty:
            continue
        alpha = policy_alpha(tag)
        ax.plot(
            subset["candidate_slot"],
            subset["mean_selected_elevation_deg"],
            color=cmap(norm(alpha)),
            marker="o",
            markersize=5.5,
            linewidth=1.8,
            alpha=0.9,
        )
    ax.set_xticks(range(10), [f"{slot}\n({slot + 3})" for slot in range(10)])
    ax.set_xlabel("Candidate slot (discrete action ID)")
    ax.set_ylabel("Mean selected target elevation [deg]")
    finish_axis(ax)
    add_alpha_colorbar(fig, ax, norm, cmap, colorbar)
    save_figure(fig, out_dir, "image_candidate_slot_elevation_vs_alpha")

    fig, ax = plt.subplots(figsize=(8.2, 4.8), constrained_layout=True)
    for tag in POLICY_ORDER:
        subset = candidates[candidates["policy_tag"] == tag].sort_values("candidate_slot")
        if subset.empty:
            continue
        alpha = policy_alpha(tag)
        ax.plot(
            subset["candidate_slot"],
            subset["acquisition_success_rate"],
            color=cmap(norm(alpha)),
            marker="o",
            markersize=5.5,
            linewidth=1.8,
            alpha=0.9,
        )
    ax.set_xticks(range(10), [f"{slot}\n({slot + 3})" for slot in range(10)])
    ax.set_xlabel("Candidate slot (discrete action ID)")
    ax.set_ylabel("Imaging acquisition success fraction")
    finish_axis(ax)
    add_alpha_colorbar(fig, ax, norm, cmap, colorbar)
    save_figure(fig, out_dir, "image_candidate_slot_success_vs_alpha")


def plot_target_selection_geometry(
    summary: pd.DataFrame, out_dir: Path, colorbar: bool
) -> None:
    plot_alpha_metric(
        summary,
        out_dir,
        "mean_initial_ang_error",
        "Mean initial pointing error [deg]",
        "initial_pointing_error_vs_alpha",
        marker="D",
        colorbar=colorbar,
    )
    plot_alpha_metric(
        summary,
        out_dir,
        "mean_target_elevation_local",
        "Mean selected target elevation [deg]",
        "selected_target_elevation_vs_alpha",
        marker="^",
        colorbar=colorbar,
    )

    distance_summary = summary.copy()
    for suffix in ("mean", "std"):
        distance_summary[f"mean_target_distance_{suffix}"] /= 1000.0
    plot_alpha_metric(
        distance_summary,
        out_dir,
        "mean_target_distance",
        "Mean selected target range [km]",
        "selected_target_range_vs_alpha",
        marker="s",
        colorbar=colorbar,
    )


def plot_priority_event_response(
    summary: pd.DataFrame, out_dir: Path, colorbar: bool
) -> bool:
    """Plot exact HIO/SHIO response only when instrumented evaluations exist."""
    required = [
        "time_to_first_hio_success_sec_mean",
        "time_to_first_shio_success_sec_mean",
    ]
    if not all(column in summary for column in required):
        return False
    if not any(summary[column].notna().any() for column in required):
        return False
    cmap = plt.get_cmap(COLORMAP)
    norm = Normalize(0.0, 1.0)
    x = summary["alpha"].to_numpy(dtype=float)
    fig, ax = plt.subplots(figsize=(8.0, 4.7), constrained_layout=True)
    for metric, label, marker in (
        ("time_to_first_hio_success_sec", "HIO", "o"),
        ("time_to_first_shio_success_sec", "SHIO", "*"),
    ):
        y = summary[mean_col(summary, metric)].to_numpy(dtype=float) / 60.0
        ystd = summary[std_col(summary, metric)].to_numpy(dtype=float) / 60.0
        ax.errorbar(x, y, yerr=ystd, fmt="none", ecolor="0.25", capsize=CAPSIZE)
        ax.scatter(
            x,
            y,
            c=x,
            cmap=cmap,
            norm=norm,
            marker=marker,
            s=90 if marker != "*" else 160,
            edgecolor="k",
            linewidth=0.75,
            label=label,
        )
    ax.set_ylabel("Time from priority injection to first capture [min]")
    ax.legend(framealpha=0.92)
    finish_axis(ax, r"Downlink reward weight $\alpha$")
    add_alpha_colorbar(fig, ax, norm, cmap, colorbar)
    save_figure(fig, out_dir, "hio_shio_first_capture_latency_vs_alpha")
    return True


def _plot_gaussian_reward_scatter(
    per_run: pd.DataFrame,
    out_dir: Path,
    *,
    x_metric: str,
    x_label: str,
    stem: str,
    colorbar: bool,
    x_divisor: float = 1.0,
    selected_only: bool = False,
) -> None:
    """Plot per-policy reward populations with two-sigma covariance ellipses."""
    cmap = plt.get_cmap(COLORMAP)
    norm = Normalize(0.0, 1.0)
    selected_alphas = {0.0, 0.1, 0.5, 0.75, 1.0}

    data = per_run.copy()
    data["alpha"] = data["policy_tag"].map(policy_alpha)
    data["scatter_x"] = pd.to_numeric(data[x_metric], errors="coerce") / x_divisor
    data["scatter_y"] = pd.to_numeric(
        data["score_ground_value_100d00i"], errors="coerce"
    )
    data = data[np.isfinite(data["scatter_x"]) & np.isfinite(data["scatter_y"])]
    if selected_only:
        data = data[data["alpha"].isin(selected_alphas)].copy()

    fig, ax = plt.subplots(figsize=(8.35, 5.0), constrained_layout=True)
    ax.scatter(
        data["scatter_x"],
        data["scatter_y"],
        c=data["alpha"],
        cmap=cmap,
        norm=norm,
        s=21,
        alpha=0.68,
        edgecolor="none",
        zorder=2,
    )

    stats_rows: list[dict[str, float | int | str]] = []
    for policy_tag in POLICY_ORDER:
        group = data[data["policy_tag"] == policy_tag]
        if group.empty:
            continue
        alpha = policy_alpha(policy_tag)
        color = cmap(norm(alpha))
        xvals = group["scatter_x"].to_numpy(dtype=float)
        yvals = group["scatter_y"].to_numpy(dtype=float)
        mean_x = float(np.mean(xvals))
        mean_y = float(np.mean(yvals))
        std_x = float(np.std(xvals, ddof=1)) if len(group) > 1 else 0.0
        std_y = float(np.std(yvals, ddof=1)) if len(group) > 1 else 0.0
        corr = (
            float(np.corrcoef(xvals, yvals)[0, 1])
            if len(group) > 1 and std_x > 0 and std_y > 0
            else np.nan
        )
        stats_rows.append(
            {
                "policy_tag": policy_tag,
                "alpha": alpha,
                "x_mean": mean_x,
                "x_std": std_x,
                "ground_reward_mean": mean_y,
                "ground_reward_std": std_y,
                "x_reward_corr": corr,
                "n_runs": int(len(group)),
            }
        )

        if len(group) >= 3 and std_x > 0 and std_y > 0:
            cov = np.cov(np.column_stack([xvals, yvals]), rowvar=False)
            eigvals, eigvecs = np.linalg.eigh(cov)
            order = eigvals.argsort()[::-1]
            eigvals = eigvals[order]
            eigvecs = eigvecs[:, order]
            angle = math.degrees(math.atan2(eigvecs[1, 0], eigvecs[0, 0]))
            width, height = 4.0 * np.sqrt(np.maximum(eigvals, 0.0))
            ax.add_patch(
                Ellipse(
                    (mean_x, mean_y),
                    width=width,
                    height=height,
                    angle=angle,
                    facecolor="none",
                    edgecolor=color,
                    linewidth=1.65,
                    alpha=0.9,
                    zorder=3,
                )
            )

        # Smaller than the original population markers so overlapping means remain legible.
        ax.scatter(
            mean_x,
            mean_y,
            marker="o",
            s=88,
            color=color,
            alpha=1.0,
            edgecolor="k",
            linewidth=0.9,
            zorder=4,
        )
        if selected_only:
            label_offsets = {
                0.0: (8, 8),
                0.1: (8, 15),
                0.5: (8, -2),
                0.75: (8, -15),
                1.0: (8, 8),
            }
            alpha_key = round(alpha, 2)
            alpha_label = f"{alpha_key:.2f}".rstrip("0").rstrip(".")
            ax.annotate(
                alpha_label,
                (mean_x, mean_y),
                xytext=label_offsets.get(alpha_key, (8, 8)),
                textcoords="offset points",
                color=color,
                fontsize=11,
                fontweight="bold",
                bbox={"facecolor": "white", "edgecolor": "none", "alpha": 0.78, "pad": 1.2},
                zorder=5,
            )

    stats = pd.DataFrame(stats_rows).sort_values("alpha")
    stats.to_csv(out_dir / f"{stem}_population_stats.csv", index=False)
    (out_dir / f"{stem}_population_stats.md").write_text(
        "```text\n" + stats.round(4).to_string(index=False) + "\n```\n",
        encoding="utf-8",
    )

    legend_blue = "#2C7BB6"
    mean_handle = Line2D(
        [0],
        [0],
        marker="o",
        color="none",
        markerfacecolor=legend_blue,
        markeredgecolor="k",
        markersize=8,
        label="Policy-population mean",
    )
    ellipse_handle = Line2D(
        [0],
        [0],
        color=legend_blue,
        linewidth=1.65,
        label="2$\\sigma$ covariance outline",
    )
    ax.legend(handles=[mean_handle, ellipse_handle], loc="best", framealpha=0.92)
    ax.set_xlabel(x_label)
    ax.set_ylabel("Ground reward")
    title_prefix = "Selected policies " if selected_only else ""
    ax.set_title(f"{title_prefix}evaluated with $\\alpha = 1.0$")
    finish_axis(ax)
    add_alpha_colorbar(fig, ax, norm, cmap, colorbar)
    save_figure(fig, out_dir, stem)


def plot_priority_behavior(summary: pd.DataFrame, per_run: pd.DataFrame, out_dir: Path, colorbar: bool) -> None:
    cmap = plt.get_cmap(COLORMAP)
    norm = Normalize(0.0, 1.0)
    x = summary["alpha"].to_numpy(dtype=float)
    y = summary[mean_col(summary, "mean_target_priority")].to_numpy(dtype=float)
    ystd = summary[std_col(summary, "mean_target_priority")].to_numpy(dtype=float)
    fig, ax = plt.subplots(figsize=(7.8, 4.65), constrained_layout=True)
    ax.fill_between(x, y - ystd, y + ystd, color="tab:green", alpha=FILL_ALPHA)
    ax.errorbar(x, y, yerr=ystd, fmt="none", ecolor="0.25", capsize=CAPSIZE, alpha=0.65)
    ax.scatter(x, y, c=x, cmap=cmap, norm=norm, marker="*", s=170, edgecolor="k", linewidth=0.8)
    ax.set_ylabel("Mean chosen target priority")
    finish_axis(ax, r"Downlink reward weight $\alpha$")
    add_alpha_colorbar(fig, ax, norm, cmap, colorbar)
    save_figure(fig, out_dir, "chosen_target_priority_vs_alpha")

    scatter_specs = [
        (
            "mean_target_priority",
            "Mean chosen target priority",
            "priority_reward_scatter",
            1.0,
        ),
        (
            "image_to_next_reward_downlink_latency_median_sec",
            "Median latency to value downlink [min]",
            "latency_reward_scatter",
            60.0,
        ),
        (
            "mean_est_images_removed_per_storage_downlink",
            "Mean downlinked images per successful storage-reducing downlink",
            "downlinked_images_per_successful_downlink_reward_scatter",
            1.0,
        ),
    ]
    for x_metric, x_label, stem, x_divisor in scatter_specs:
        _plot_gaussian_reward_scatter(
            per_run,
            out_dir,
            x_metric=x_metric,
            x_label=x_label,
            stem=stem,
            x_divisor=x_divisor,
            selected_only=False,
            colorbar=colorbar,
        )
        _plot_gaussian_reward_scatter(
            per_run,
            out_dir,
            x_metric=x_metric,
            x_label=x_label,
            stem=f"{stem}_selected_alphas",
            x_divisor=x_divisor,
            selected_only=True,
            colorbar=colorbar,
        )


def plot_umbra_behavior(summary: pd.DataFrame, out_dir: Path, colorbar: bool) -> None:
    cmap = plt.get_cmap(COLORMAP)
    norm = Normalize(0.0, 1.0)
    x = summary["alpha"].to_numpy(dtype=float)
    metrics = [
        ("umbra_smart_fraction", "Smart umbra fraction", "o"),
        ("umbra_mean_sun_target_dot", "Mean sun-target dot", "s"),
    ]
    fig, ax = plt.subplots(figsize=(7.9, 4.75), constrained_layout=True)
    for metric, label, marker in metrics:
        y = summary[mean_col(summary, metric)].to_numpy(dtype=float)
        ystd = summary[std_col(summary, metric)].to_numpy(dtype=float)
        ax.errorbar(x, y, yerr=ystd, fmt="none", ecolor="0.25", capsize=CAPSIZE, alpha=0.55)
        ax.scatter(
            x,
            y,
            c=x,
            cmap=cmap,
            norm=norm,
            marker=marker,
            s=82,
            edgecolor="k",
            linewidth=0.8,
            label=label,
        )
    ax.set_ylabel("Fraction / dot product")
    finish_axis(ax, r"Downlink reward weight $\alpha$")
    ax.legend(framealpha=0.92)
    add_alpha_colorbar(fig, ax, norm, cmap, colorbar)
    save_figure(fig, out_dir, "umbra_smart_and_dot_vs_alpha")

    plot_alpha_metric(
        summary,
        out_dir,
        "umbra_mean_sun_target_sep_deg",
        "Mean sun-target separation [deg]",
        "umbra_sun_target_separation_vs_alpha",
        marker="D",
        colorbar=colorbar,
    )


def format_alpha(alpha: float) -> str:
    return f"{alpha:.2f}".rstrip("0").rstrip(".")


def load_summary_for_comparison(root: Path) -> pd.DataFrame:
    detailed_dir = root.expanduser().resolve() / "analysis_detailed"
    return normalize_summary(pd.read_csv(detailed_dir / "detailed_summary_by_policy.csv"))


def add_comparison_colorbar(fig: plt.Figure, ax: plt.Axes, norm: Normalize, cmap) -> None:
    sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax, pad=0.025, fraction=0.045)
    cbar.set_label(r"Downlink reward weight $\alpha$", labelpad=8)


def annotate_alpha_points(ax: plt.Axes, rows: pd.DataFrame) -> None:
    offsets = {
        0.0: (16, 10),
        0.1: (18, 20),
        0.2: (-36, 8),
        0.3: (18, -18),
        0.4: (14, -30),
        0.5: (-44, 0),
        0.75: (-42, -28),
        1.0: (14, 16),
    }
    for _, row in rows.iterrows():
        alpha = float(row["alpha"])
        ax.annotate(
            format_alpha(alpha),
            (float(row["x_value"]), float(row["y_value"])),
            xytext=offsets.get(round(alpha, 2), (8, 8)),
            textcoords="offset points",
            fontsize=10,
            color="0.12",
            bbox={"facecolor": "white", "edgecolor": "none", "alpha": 0.76, "pad": 1.1},
            zorder=5,
        )


def plot_comparison_scatter(
    summary_100: pd.DataFrame,
    summary_200: pd.DataFrame,
    out_dir: Path,
    *,
    metric: str,
    label: str,
    stem: str,
    divisor: float = 1.0,
    reference_multiplier: float = 1.0,
) -> None:
    merged = summary_100[["policy_tag", "alpha", mean_col(summary_100, metric)]].merge(
        summary_200[["policy_tag", mean_col(summary_200, metric)]],
        on="policy_tag",
        suffixes=("_100", "_200"),
    )
    merged["x_value"] = merged[f"{metric}_mean_100"] / divisor
    merged["y_value"] = merged[f"{metric}_mean_200"] / divisor
    merged = merged[np.isfinite(merged["x_value"]) & np.isfinite(merged["y_value"])]

    cmap = plt.get_cmap("viridis")
    norm = Normalize(0.0, 1.0)
    fig, ax = plt.subplots(figsize=(7.95, 5.35), constrained_layout=True)
    ax.scatter(
        merged["x_value"],
        merged["y_value"],
        c=merged["alpha"],
        cmap=cmap,
        norm=norm,
        s=115,
        edgecolor="k",
        linewidth=0.75,
        zorder=3,
    )
    x_min = float(merged["x_value"].min())
    x_max = float(merged["x_value"].max())
    y_min = float(merged["y_value"].min())
    y_max = float(merged["y_value"].max())
    x_pad = 0.13 * max(x_max - x_min, 1.0)
    y_pad = 0.18 * max(y_max - y_min, 1.0)
    x0, x1 = x_min - x_pad, x_max + x_pad
    y0, y1 = y_min - y_pad, y_max + y_pad
    ax.set_xlim(x0, x1)
    ax.set_ylim(y0, y1)

    def add_reference(multiplier: float, label: str, linestyle: str, color: str) -> None:
        start = max(x0, y0 / multiplier)
        end = min(x1, y1 / multiplier)
        if start >= end:
            return
        xs = np.array([start, end])
        ys = multiplier * xs
        ax.plot(xs, ys, color=color, linestyle=linestyle, linewidth=1.1, alpha=0.65)
        ax.annotate(
            label,
            (xs[-1], ys[-1]),
            xytext=(-30, -18),
            textcoords="offset points",
            color=color,
        )

    add_reference(1.0, "1:1", "--", "0.28")
    if reference_multiplier != 1.0:
        add_reference(reference_multiplier, f"{reference_multiplier:g}x", ":", "0.45")
    annotate_alpha_points(ax, merged)
    ax.set_xlabel(f"{label}, 100 targets")
    ax.set_ylabel(f"{label}, 200 targets")
    ax.set_title(f"{label}: 100-target vs 200-target MC")
    finish_axis(ax)
    add_comparison_colorbar(fig, ax, norm, cmap)
    save_figure(fig, out_dir, stem)


def plot_reward_image_frontier(
    summary_100: pd.DataFrame,
    summary_200: pd.DataFrame,
    out_dir: Path,
) -> None:
    rows = []
    for label, n_targets, summary, marker in (
        ("100 targets", 100, summary_100, "o"),
        ("200 targets", 200, summary_200, "s"),
    ):
        for _, row in summary.iterrows():
            rows.append(
                {
                    "target_count": label,
                    "n_targets": n_targets,
                    "policy_tag": str(row["policy_tag"]),
                    "alpha": float(row["alpha"]),
                    "confirmed_per_target": row["confirmed_illuminated_images_mean"] / n_targets,
                    "ground_reward": row["score_ground_value_100d00i_mean"],
                    "marker": marker,
                }
            )
    data = pd.DataFrame(rows)
    cmap = plt.get_cmap("viridis")
    norm = Normalize(0.0, 1.0)
    fig, ax = plt.subplots(figsize=(8.35, 5.35), constrained_layout=True)
    for label, marker in (("100 targets", "o"), ("200 targets", "s")):
        subset = data[data["target_count"] == label]
        ax.plot(
            subset["confirmed_per_target"],
            subset["ground_reward"],
            color="0.22",
            linewidth=0.9,
            alpha=0.35,
            zorder=1,
        )
        ax.scatter(
            subset["confirmed_per_target"],
            subset["ground_reward"],
            c=subset["alpha"],
            cmap=cmap,
            norm=norm,
            marker=marker,
            s=105,
            edgecolor="k",
            linewidth=0.75,
            label=label,
            zorder=3,
        )
    ax.set_xlabel("Confirmed illuminated images per target")
    ax.set_ylabel("Ground reward")
    ax.set_title("Reward frontier normalized by catalog size")
    ax.legend(loc="upper left", framealpha=0.93)
    finish_axis(ax)
    add_comparison_colorbar(fig, ax, norm, cmap)
    save_figure(fig, out_dir, "comparison_reward_frontier_per_target_100_vs_200")


def plot_target_count_comparisons(
    summary_100: pd.DataFrame,
    summary_200: pd.DataFrame,
    out_dir: Path,
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    plot_comparison_scatter(
        summary_100,
        summary_200,
        out_dir,
        metric="score_ground_value_100d00i",
        label="Ground reward",
        stem="comparison_ground_reward_100_vs_200",
    )
    plot_comparison_scatter(
        summary_100,
        summary_200,
        out_dir,
        metric="confirmed_illuminated_images",
        label="Confirmed illuminated images",
        stem="comparison_confirmed_images_100_vs_200",
        reference_multiplier=2.0,
    )
    plot_comparison_scatter(
        summary_100,
        summary_200,
        out_dir,
        metric="illuminated_images",
        label="Illuminated images",
        stem="comparison_illuminated_images_100_vs_200",
        reference_multiplier=2.0,
    )
    plot_comparison_scatter(
        summary_100,
        summary_200,
        out_dir,
        metric="image_to_next_reward_downlink_latency_median_sec",
        label="Median image-to-value downlink latency [s]",
        stem="comparison_downlink_latency_100_vs_200",
    )
    plot_reward_image_frontier(summary_100, summary_200, out_dir)

    readme = [
        "# AMOS 2026 GAT 100-vs-200 Target Comparison Figures",
        "",
        "Figures compare the completed eight-policy MC set only:",
        ", ".join(POLICY_ORDER),
        "",
        "Comparison plots use viridis to encode the trained downlink reward weight alpha.",
        "Every figure is exported as `.png` and `.pdf`.",
    ]
    (out_dir / "README.md").write_text("\n".join(readme), encoding="utf-8")


def write_plot_manifest(out_dir: Path, input_root: Path, detailed_dir: Path) -> None:
    figure_files = sorted(p.name for p in out_dir.glob("*.png"))
    manifest = [
        "# AMOS 2026 GAT Research Figure Manifest",
        "",
        f"Input root: `{input_root}`",
        f"Detailed analysis: `{detailed_dir}`",
        "",
        "Generated figures are saved as both `.png` and `.pdf` unless noted.",
        "",
    ]
    for name in figure_files:
        manifest.append(f"- `{name}`")
    if (out_dir / "priority_reward_scatter_population_stats.csv").exists():
        manifest.append("")
        manifest.append("Additional table outputs:")
        manifest.append("- `priority_reward_scatter_population_stats.csv`")
        manifest.append("- `priority_reward_scatter_population_stats.md`")
    manifest.extend(
        [
            "",
            "## Metric Availability",
            "",
            "Available exactly from the existing 800-run archive:",
            "",
            "- Imaging slew and action durations, acquisition success, initial pointing error, selected elevation/range/priority.",
            "- Action-ID and candidate-slot frequencies; slots normally follow ascending local elevation, with padding by nearest eligible targets when fewer than ten are visible.",
            "- Downlink duration and outcome split: storage reduced, commanded with empty storage, or commanded with nonempty storage but no transfer.",
            "- Battery, storage, illumination, umbra-decision, reward, and aggregate priority behavior.",
            "",
            "Requires a new evaluation sweep using the instrumented evaluator:",
            "",
            "- Exact HIO/SHIO identity, first-access, first-command, and first-success latency after the dynamic-priority event.",
            "- Exact image-packet-to-ground latency and exact images/priority value delivered by each downlink; current delivery latency is a next-value-downlink proxy because the archived logs lack packet IDs.",
            "",
            "Interpretation note: useful downlink fraction is the fraction of commanded downlink actions with positive 100d00i reward, not the fraction of onboard images above the illumination threshold.",
            "Interpretation note: an empty-at-command downlink is measured directly from storage at action selection. A nonempty/no-transfer downlink is different: data was onboard, but storage did not decrease during the action, usually because no useful ground-station transfer occurred.",
        ]
    )
    (out_dir / "README.md").write_text("\n".join(manifest), encoding="utf-8")


def main() -> int:
    args = parse_args()
    setup_style()
    input_root = args.input_root.expanduser().resolve()
    detailed_dir = (args.detailed_dir or input_root / "analysis_detailed").expanduser().resolve()
    out_dir = (args.output_dir or input_root / "analysis_research_plots").expanduser().resolve()
    colorbar = not args.no_colorbar

    run_detailed_if_needed(
        input_root,
        detailed_dir,
        args.expected_seeds,
        args.storage_capacity_images,
        args.force_detailed,
    )

    summary = normalize_summary(pd.read_csv(detailed_dir / "detailed_summary_by_policy.csv"))
    per_run = pd.read_csv(detailed_dir / "detailed_per_run.csv")
    per_run = per_run[per_run["policy_tag"].isin(POLICY_ORDER)].copy()
    actions = read_csv_or_empty(detailed_dir / "action_distribution_by_policy.csv")
    downlinks = pd.read_csv(detailed_dir / "downlink_summary_by_policy.csv")
    candidates = read_csv_or_empty(
        detailed_dir / "image_candidate_slot_summary_by_policy.csv"
    )

    plot_alpha_metric(
        summary,
        out_dir,
        "score_ground_value_100d00i",
        "Ground reward",
        "ground_value_reward_vs_alpha",
        marker="o",
        colorbar=colorbar,
    )
    plot_ground_value_score_boxplot(per_run, out_dir, colorbar)
    plot_reward_images_combined(summary, out_dir, colorbar)
    plot_image_status(summary, out_dir, colorbar)
    plot_action_distribution(actions, out_dir)
    plot_action_outcome_stacked_fraction(per_run, out_dir)
    plot_downlink_usefulness(downlinks, out_dir, colorbar)
    plot_downlink_value_density(per_run, out_dir, colorbar)
    plot_latency(downlinks, out_dir, colorbar)
    plot_imaging_timing(summary, out_dir, colorbar)
    plot_downlink_outcomes(downlinks, out_dir, colorbar)
    plot_action_outcome_boxplot(per_run, out_dir)
    plot_candidate_slot_behavior(candidates, out_dir, colorbar)
    plot_target_selection_geometry(summary, out_dir, colorbar)
    if not plot_priority_event_response(summary, out_dir, colorbar):
        print(
            "HIO/SHIO response plot skipped: the existing MC archive predates exact "
            "priority-event target logging."
        )
    plot_priority_behavior(summary, per_run, out_dir, colorbar)
    plot_umbra_behavior(summary, out_dir, colorbar)
    write_plot_manifest(out_dir, input_root, detailed_dir)

    print(f"Research plots written to: {out_dir}")
    if args.comparison_root is not None:
        comparison_root = args.comparison_root.expanduser().resolve()
        comparison_out_dir = (
            args.comparison_output_dir
            or input_root / "analysis_research_plots_compare_100targets"
        ).expanduser().resolve()
        comparison_summary = load_summary_for_comparison(comparison_root)
        plot_target_count_comparisons(comparison_summary, summary, comparison_out_dir)
        print(f"Comparison plots written to: {comparison_out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
