"""Dependency-free constants for the matched AMOS 2025 300-second MC."""

CATALOG_SIZE = 100
CANDIDATE_COUNT = 10
SEED_START = 0
SEED_STOP_INCLUSIVE = 99
SEEDS_PER_METHOD = SEED_STOP_INCLUSIVE - SEED_START + 1
METHODS = (
    "breckenridge2026_alpha0_mlp",
    "target_set_attention",
    "smallest_angle_heuristic",
    "closest_distance_heuristic",
)
TOTAL_TASKS = len(METHODS) * SEEDS_PER_METHOD

EPISODE_DURATION_S = 45_000.0
IMAGING_DURATION_S = 300.0
CHARGE_DURATION_S = 300.0
DOWNLINK_DURATION_S = 180.0
DESATURATION_DURATION_S = 150.0
INITIAL_BATTERY_FRACTION = (0.10, 0.40)
REWARD_ALPHA = 0.0
BRECKENRIDGE_ALPHA0_CHECKPOINT_ITERATION = 145
BRECKENRIDGE_ALPHA0_MODULE_STATE_SHA256 = (
    "0d8033272f14cdd408192d7ab6ee819b18691c9385fca87be24044fc950464d2"
)
BRECKENRIDGE_ALPHA0_TRAINABLE_PARAMETERS = 8_757_262

__all__ = [
    "CANDIDATE_COUNT",
    "BRECKENRIDGE_ALPHA0_CHECKPOINT_ITERATION",
    "BRECKENRIDGE_ALPHA0_MODULE_STATE_SHA256",
    "BRECKENRIDGE_ALPHA0_TRAINABLE_PARAMETERS",
    "CATALOG_SIZE",
    "CHARGE_DURATION_S",
    "DESATURATION_DURATION_S",
    "DOWNLINK_DURATION_S",
    "EPISODE_DURATION_S",
    "IMAGING_DURATION_S",
    "INITIAL_BATTERY_FRACTION",
    "METHODS",
    "REWARD_ALPHA",
    "SEEDS_PER_METHOD",
    "SEED_START",
    "SEED_STOP_INCLUSIVE",
    "TOTAL_TASKS",
]
