"""Constants for the frozen AMOS 2025 policy transfer Monte Carlo."""

CATALOG_SIZES = (100, 200, 400)
SEED_START = 0
SEED_STOP_INCLUSIVE = 99
SEEDS_PER_CATALOG = SEED_STOP_INCLUSIVE - SEED_START + 1
TOTAL_TASKS = len(CATALOG_SIZES) * SEEDS_PER_CATALOG
METHOD = "legacy_amos2025_alpha0_policy"
CANDIDATE_COUNT = 10
TRAINED_IMAGING_DURATION_S = 300.0
EVALUATION_IMAGING_DURATION_S = 100.0
EXPECTED_OBSERVATION_SIZE = 87
EXPECTED_ACTION_COUNT = 13
EXPECTED_TRAINABLE_PARAMETERS = 2_293_774
EXPECTED_MODULE_STATE_SHA256 = (
    "6db5bcd4fda20205977dfab377441f625051ef9e9dfaebde5e8db5ec1ab0e2c4"
)
POLICY_FAMILY = "wGAE_balance0d100i_largepenalties_smallbatch_obs2"
POLICY_BEST_ITERATION = 427

__all__ = [
    "CANDIDATE_COUNT",
    "CATALOG_SIZES",
    "EVALUATION_IMAGING_DURATION_S",
    "EXPECTED_ACTION_COUNT",
    "EXPECTED_MODULE_STATE_SHA256",
    "EXPECTED_OBSERVATION_SIZE",
    "EXPECTED_TRAINABLE_PARAMETERS",
    "METHOD",
    "POLICY_BEST_ITERATION",
    "POLICY_FAMILY",
    "SEEDS_PER_CATALOG",
    "SEED_START",
    "SEED_STOP_INCLUSIVE",
    "TOTAL_TASKS",
    "TRAINED_IMAGING_DURATION_S",
]
