"""Local RSO product provenance and catalog knowledge.

The standard BSK-RL :class:`~bsk_rl.data.DataStore` remains the owner of these
objects. This module deliberately contains no second product-store or global-ledger
abstraction: physical image data live in the observing spacecraft's Basilisk storage
unit, product metadata live in that spacecraft's data store, and team accounting lives
inside the global rewarder.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from typing import Iterable, Mapping, Optional


@dataclass(frozen=True, slots=True)
class ImageProductRecord:
    """Metadata for one physical image product with immutable provenance."""

    record_id: str
    source_sensor: str
    target_id: int
    capture_time: float
    delivery_time: Optional[float]
    quality: float
    storage_owner: str

    def delivered(self, delivery_time: float) -> "ImageProductRecord":
        """Return a delivered copy while preserving capture provenance."""
        return replace(self, delivery_time=float(delivery_time))


@dataclass(slots=True)
class LocalTargetKnowledge:
    """One sensor's latest local or explicitly received target status."""

    target_id: int
    latest_acquisition_time: Optional[float] = None
    latest_delivery_time: Optional[float] = None
    cooldown_until: float = float("-inf")
    local_cooldown_until: float = float("-inf")
    remote_cooldown_until_by_source: dict[str, float] = field(default_factory=dict)
    pending_record_ids: tuple[str, ...] = ()
    remote_pending_sources: tuple[str, ...] = ()
    remote_pending_expiry_by_source: dict[str, float] = field(default_factory=dict)
    last_update_time: float = float("-inf")
    last_update_source: Optional[str] = None


class LocalCatalogKnowledge:
    """Catalog state owned by one sensing spacecraft's standard data store."""

    def __init__(self, sensor_id: str, target_ids: Iterable[int]) -> None:
        """Create one local entry for every catalog target."""
        self.sensor_id = str(sensor_id)
        self._targets = {
            int(target_id): LocalTargetKnowledge(target_id=int(target_id))
            for target_id in target_ids
        }

    @property
    def targets(self) -> Mapping[int, LocalTargetKnowledge]:
        """Return the sensor-local target knowledge mapping."""
        return self._targets

    def target(self, target_id: int) -> LocalTargetKnowledge:
        """Return local knowledge for one target ID."""
        return self._targets[int(target_id)]

    @staticmethod
    def _refresh_effective_state(state: LocalTargetKnowledge, sim_time: float) -> None:
        active_remote_pending = {
            source: expiry
            for source, expiry in state.remote_pending_expiry_by_source.items()
            if float(expiry) >= float(sim_time)
        }
        state.remote_pending_expiry_by_source = active_remote_pending
        state.remote_pending_sources = tuple(sorted(active_remote_pending))
        state.cooldown_until = max(
            [
                state.local_cooldown_until,
                *state.remote_cooldown_until_by_source.values(),
            ],
            default=float("-inf"),
        )

    def is_privately_eligible(self, target_id: int, sim_time: float) -> bool:
        """Evaluate eligibility using only events generated by this sensor."""
        state = self.target(target_id)
        return not state.pending_record_ids and sim_time >= state.local_cooldown_until

    def is_eligible(self, target_id: int, sim_time: float) -> bool:
        """Evaluate only local and received knowledge, never global reward truth."""
        state = self.target(target_id)
        self._refresh_effective_state(state, sim_time)
        return (
            self.is_privately_eligible(target_id, sim_time)
            and not state.remote_pending_sources
            and sim_time >= state.cooldown_until
        )

    def record_capture(self, product: ImageProductRecord) -> None:
        """Record one locally produced, physically onboard image product."""
        if product.source_sensor != self.sensor_id:
            raise ValueError("A local capture must originate at the local sensor.")
        state = self.target(product.target_id)
        state.pending_record_ids = tuple(
            dict.fromkeys((*state.pending_record_ids, product.record_id))
        )
        previous = state.latest_acquisition_time
        state.latest_acquisition_time = (
            product.capture_time
            if previous is None
            else max(previous, product.capture_time)
        )
        state.last_update_time = product.capture_time
        state.last_update_source = self.sensor_id

    def record_delivery(
        self,
        product: ImageProductRecord,
        cooldown_until: Optional[float] = None,
    ) -> None:
        """Record ground delivery of a product owned by this sensor."""
        if product.delivery_time is None:
            raise ValueError("Delivered local knowledge requires a delivery timestamp.")
        state = self.target(product.target_id)
        state.pending_record_ids = tuple(
            record_id
            for record_id in state.pending_record_ids
            if record_id != product.record_id
        )
        previous = state.latest_delivery_time
        state.latest_delivery_time = (
            product.delivery_time
            if previous is None
            else max(previous, product.delivery_time)
        )
        if cooldown_until is not None:
            state.local_cooldown_until = max(
                state.local_cooldown_until, float(cooldown_until)
            )
        self._refresh_effective_state(state, product.delivery_time)
        state.last_update_time = product.delivery_time
        state.last_update_source = self.sensor_id

    def merge_status(
        self,
        *,
        target_id: int,
        acquisition_time: Optional[float],
        delivery_time: Optional[float],
        cooldown_until: Optional[float],
        lifecycle_status: Optional[str],
        update_time: float,
        expiry_time: Optional[float],
        source_sensor: str,
    ) -> bool:
        """Merge a compact received status deterministically when it is newer."""
        state = self.target(target_id)
        update_key = (float(update_time), str(source_sensor))
        current_key = (state.last_update_time, state.last_update_source or "")
        if update_key <= current_key:
            return False
        if acquisition_time is not None:
            state.latest_acquisition_time = (
                float(acquisition_time)
                if state.latest_acquisition_time is None
                else max(state.latest_acquisition_time, float(acquisition_time))
            )
        if delivery_time is not None:
            state.latest_delivery_time = (
                float(delivery_time)
                if state.latest_delivery_time is None
                else max(state.latest_delivery_time, float(delivery_time))
            )

        source = str(source_sensor)
        if cooldown_until is not None:
            state.remote_cooldown_until_by_source[source] = max(
                state.remote_cooldown_until_by_source.get(source, float("-inf")),
                float(cooldown_until),
            )
        elif lifecycle_status in {"delivered", "eligible"}:
            state.remote_cooldown_until_by_source.pop(source, None)

        if lifecycle_status == "pending_verification":
            state.remote_pending_expiry_by_source[source] = float(
                expiry_time if expiry_time is not None else update_time
            )
        elif lifecycle_status in {"delivered", "eligible", "cooldown"}:
            state.remote_pending_expiry_by_source.pop(source, None)

        self._refresh_effective_state(state, update_time)
        state.last_update_time = float(update_time)
        state.last_update_source = source
        return True


__all__ = ["ImageProductRecord", "LocalCatalogKnowledge", "LocalTargetKnowledge"]
