import os
from bsk_rl.training.mcts.mcts_train import run_experiment
from pathlib import Path

SEP = os.path.sep

if __name__ == "__main__":
    """
    This scripts provides an example of how to perform a hyperparameter search of a
    state-action value network trained with data generated from MCTS. This script should
    only be run after this data has been generated by MCTS using the
    `mcts_data_generator.py` script.
    """

    data_directory = (
        ".."
        + SEP
        + ".."
        + SEP
        + "bsk_rl"
        + SEP
        + "results"
        + SEP
        + "mcts"
        + SEP
        + "AgileEOS"
        + SEP
        + "MCTS-Train Test"
        + SEP
    )

    data_directory = str(Path(__file__).parent.resolve() / data_directory)

    layers = [1, 2]
    net_sizes = [10, 20]
    dropouts = [None]
    activations = ["tanh"]
    alphas = [0.1]

    epoch_num = [100]

    parameters = {
        "net_sizes": net_sizes,
        "layers": layers,
        "activations": activations,
        "dropouts": dropouts,
        "alphas": alphas,
        "epoch_num": epoch_num,
    }

    run_experiment(data_directory, parameters)
